-- ============================================================================
-- ADAM → FieldMaps admin crosswalk
-- ============================================================================
-- Static reference table mapping each WFP ADAM admin unit to its canonical
-- FieldMaps (FM) p-code, so ADAM exposure can be reported against
-- standardized FM admin boundaries.
--
-- Built offline, NOT by the runtime pipelines: scripts/build_adam_fm_lookup.py
-- reads the human-reviewed crosswalk
-- (data/review/adam_fm_crosswalk_humanreview.csv — the source of truth for
-- reviewer decisions) and projects it into these lookup rows. The crosswalk
-- itself is generated by scripts/build_adam_fm_crosswalk.py. (The spatial
-- matcher in src/static/adam/matcher.py is REVIEW-ONLY and is NOT used by this
-- build.) Rebuild via scripts/init_db_adam_lookup.py (drop+recreate) then the
-- builder; rebuild only when FieldMaps or ADAM change their admin schema.
--
-- Downstream join: storms.adam_exposure.admin_name = adam_fm_lookup.adam_admin_name
-- to attach (fm_pcode, fm_name) → adam_exposure.pcode.
--
-- Natural key: (iso3, admin_level, fm_pcode, adam_admin_id), NULLS NOT
-- DISTINCT so an FM-only row (NULL adam_admin_id) can't silently duplicate.
-- ============================================================================

DROP TABLE IF EXISTS storms.adam_fm_lookup CASCADE;

CREATE TABLE IF NOT EXISTS storms.adam_fm_lookup
(
    iso3            TEXT,
    admin_level     BIGINT,
    fm_pcode        TEXT,
    fm_name         TEXT,
    adam_admin_id   BIGINT,
    adam_admin_name TEXT,
    iou             DOUBLE PRECISION,
    caveat_kind     TEXT,
    caveat_note     TEXT,
    CONSTRAINT adam_fm_lookup_unique
        UNIQUE NULLS NOT DISTINCT (iso3, admin_level, fm_pcode, adam_admin_id)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS storms.adam_fm_lookup
    OWNER to {owner};

COMMENT ON TABLE storms.adam_fm_lookup IS
    'Static ADAM-admin → FieldMaps-pcode crosswalk. Built offline by scripts/build_adam_fm_lookup.py from the human-reviewed crosswalk; join to storms.adam_exposure on admin_name.';
COMMENT ON COLUMN storms.adam_fm_lookup.iso3 IS
    'ISO3 country code the admin unit belongs to.';
COMMENT ON COLUMN storms.adam_fm_lookup.admin_level IS
    'FieldMaps admin level the row maps at (0=country, 1=adm1, ...). The ADAM side is fixed at adm1.';
COMMENT ON COLUMN storms.adam_fm_lookup.fm_pcode IS
    'Canonical FieldMaps p-code (the match target). Nullable when no FM unit was matched (see caveat_kind).';
COMMENT ON COLUMN storms.adam_fm_lookup.fm_name IS
    'FieldMaps admin name for fm_pcode.';
COMMENT ON COLUMN storms.adam_fm_lookup.adam_admin_id IS
    'ADAM-native admin id (BIGINT). Part of the natural key; NULL on FM-only rows.';
COMMENT ON COLUMN storms.adam_fm_lookup.adam_admin_name IS
    'ADAM admin name — the join key against storms.adam_exposure.admin_name.';
COMMENT ON COLUMN storms.adam_fm_lookup.iou IS
    'Intersection-over-union of the chosen ADAM↔FM polygon pair (0..1); match confidence. 0 when no overlap.';
COMMENT ON COLUMN storms.adam_fm_lookup.caveat_kind IS
    'Match-quality / admin-level caveat. NULL means a clean 1:1 match. Observed values: aggregating_from_adam, fm_adm1_only, no_adam_at_adm1, country_only, needs_manual_mapping, aggregated_in_adam, no_adam_source.';
COMMENT ON COLUMN storms.adam_fm_lookup.caveat_note IS
    'Free-text detail accompanying caveat_kind.';

CREATE INDEX IF NOT EXISTS idx_adam_fm_lookup_admin_name
    ON storms.adam_fm_lookup (adam_admin_name) WHERE adam_admin_name IS NOT NULL;
