-- ============================================================================
-- GDACS → FieldMaps admin crosswalk
-- ============================================================================
-- Static reference table mapping each GDACS admin unit to its canonical
-- FieldMaps (FM) p-code, so GDACS exposure (keyed on GDACS-native admin
-- codes) can be reported against standardized FM admin boundaries.
--
-- Built offline, NOT by the runtime pipelines: scripts/build_gdacs_fm_lookup.py
-- reads the human-reviewed crosswalk
-- (data/review/gdacs_fm_crosswalk_humanreview.csv — the source of truth for
-- reviewer decisions) and projects it into these lookup rows. The crosswalk
-- itself is generated by scripts/build_gdacs_fm_crosswalk.py. (The spatial
-- matcher in src/static/gdacs/matcher.py is REVIEW-ONLY and is NOT used by
-- this build.) Rebuild via scripts/init_db_gdacs_lookup.py (drop+recreate)
-- then the builder; rebuild only when FieldMaps or GDACS change their schema.
--
-- Downstream join: storms.gdacs_exposure.gdacs_admin_code = gdacs_fm_lookup.gmi_admin
-- to attach (fm_pcode, fm_name). NOTE the column names differ across the two
-- sides (gdacs_exposure stores the native code as `gdacs_admin_code`, this
-- table as `gmi_admin`); the consumer maps them explicitly. A symmetric
-- rename is deferred (cross-repo: ds-storms-alerts joins on these names).
--
-- DOUBLE-COUNT CONTRACT: a single gmi_admin (coarse GDACS unit) may map to
-- MULTIPLE fm_pcode rows here (many-FM ← one-GDACS). The exposure→lookup join
-- therefore fans out, so any consumer that sums population MUST aggregate by
-- fm_pcode (e.g. groupby('fm_pcode').sum('pop_exposed')) or it will
-- double-count. Consumer lives in ds-storms-alerts (exposure_enrich.py) —
-- verify it honors this (tracked as a follow-up; see PR #19).
--
-- Natural key: (iso3, admin_level, fm_pcode, gmi_admin), NULLS NOT DISTINCT
-- so an FM-only row (NULL gmi_admin) can't silently duplicate.
-- ============================================================================

DROP TABLE IF EXISTS storms.gdacs_fm_lookup CASCADE;

CREATE TABLE IF NOT EXISTS storms.gdacs_fm_lookup
(
    iso3             TEXT,
    admin_level      BIGINT,
    fm_pcode         TEXT,
    fm_name          TEXT,
    gmi_admin        TEXT,
    gdacs_admin_name TEXT,
    caveat_kind      TEXT,
    caveat_note      TEXT,
    CONSTRAINT gdacs_fm_lookup_unique
        UNIQUE NULLS NOT DISTINCT (iso3, admin_level, fm_pcode, gmi_admin)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS storms.gdacs_fm_lookup
    OWNER to {owner};

COMMENT ON TABLE storms.gdacs_fm_lookup IS
    'Static GDACS-admin → FieldMaps-pcode crosswalk. Built offline by scripts/build_gdacs_fm_lookup.py from the human-reviewed crosswalk; join storms.gdacs_exposure.gdacs_admin_code to gdacs_fm_lookup.gmi_admin.';
COMMENT ON COLUMN storms.gdacs_fm_lookup.iso3 IS
    'ISO3 country code the admin unit belongs to.';
COMMENT ON COLUMN storms.gdacs_fm_lookup.admin_level IS
    'FieldMaps admin level the row maps at (0=country, 1=adm1, ...).';
COMMENT ON COLUMN storms.gdacs_fm_lookup.fm_pcode IS
    'Canonical FieldMaps p-code (the match target). Nullable when no FM unit was matched (see caveat_kind).';
COMMENT ON COLUMN storms.gdacs_fm_lookup.fm_name IS
    'FieldMaps admin name for fm_pcode.';
COMMENT ON COLUMN storms.gdacs_fm_lookup.gmi_admin IS
    'GDACS-native GMI admin code — the join key, matched against storms.gdacs_exposure.gdacs_admin_code (note the differing column names). Part of the natural key; NULL on FM-only rows.';
COMMENT ON COLUMN storms.gdacs_fm_lookup.gdacs_admin_name IS
    'GDACS admin name for gmi_admin.';
COMMENT ON COLUMN storms.gdacs_fm_lookup.caveat_kind IS
    'Match-quality / admin-level caveat. NULL means a clean 1:1 match. Observed values: fm_adm1_only, no_gdacs_at_adm1, aggregating_from_gdacs, country_only, aggregated_in_gdacs, needs_manual_mapping, no_fm_source.';
COMMENT ON COLUMN storms.gdacs_fm_lookup.caveat_note IS
    'Free-text detail accompanying caveat_kind (e.g. which units were aggregated).';

CREATE INDEX IF NOT EXISTS idx_gdacs_fm_lookup_gmi_admin
    ON storms.gdacs_fm_lookup (gmi_admin) WHERE gmi_admin IS NOT NULL;
