"""Spatial matching: FieldMaps adm-1 polygons ↔ GDACS admin polygons.

============================================================================
⚠️  EXPLORATORY / REVIEW-ONLY — NOT live production monitoring.
----------------------------------------------------------------------------
This module is NOT used by the production lookup or the real-time pipelines.
The production `storms.gdacs_fm_lookup` is built by
`scripts/build_gdacs_fm_lookup.py` from the human-reviewed crosswalk
(`data/review/gdacs_fm_crosswalk_humanreview.csv`); that crosswalk is
generated by `scripts/build_gdacs_fm_crosswalk.py`, which runs its own
overlay and emits EVERY FM×GDACS pair — it does not call this module.

Only caller after this PR: the human-review report pipeline
(`scripts/build_review_artifacts.py` → `exploration/review_report_gdacs.qmd`).
(The legacy v1 builder — now archived at
`scripts/_archive/build_canonical_lookup.py` — also used it.)

Consequence: the IoU best-pick tie-break below is review-only and left as-is
on purpose (see PR #19 discussion). A later PR will relocate this out of
`src/static/` so the exploratory↔production boundary is structural.
============================================================================

Pairs each FieldMaps unit with the GDACS unit that maximises
intersection-over-union (IoU) inside the country. Outputs one row per
FieldMaps polygon — even when no GDACS polygon overlaps it (those rows
get ``issue="no_overlap"`` so the caller can flag orphans).

GDACS's admin layer is fixed at admin-1 (no hierarchy) so only the
FM-side level is configurable per country (via
:func:`src.static.gdacs.inputs.resolve_gdacs_fm_level`).

This is the expensive step. Called once per country by
``scripts/build_review_artifacts.py`` (the review-report pipeline; see the
banner above) — and historically by the archived v1 lookup builder; the
whole basin takes ~minutes on a laptop.
"""

from __future__ import annotations

import logging

import geopandas as gpd

from src.static.gdacs.admin import filter_gdacs_country
from src.static.gdacs.inputs import (
    FM_ADM1_NAME_FALLBACK_ISOS,
    fallback_fm_name_from_adm0,
    fm_id_and_name_cols,
    load_fieldmaps_adm,
)


logger = logging.getLogger(__name__)


def match_country(
    iso3: str,
    gdacs: gpd.GeoDataFrame,
    low_iou: float = 0.5,
    fm_level: int = 1,
) -> list[dict]:
    """One row per FieldMaps unit-at-``fm_level`` for ``iso3``.

    Returned dict shape::

        {
          iso3, fm_level, fm_pcode, fm_name, fm_area_m2,
          fm_country_count, gdacs_country_count,
          gmi_admin, fips_admin, gdacs_admin_name, gdacs_admin_type,
          iou, gdacs_area_m2, n_candidates,
          issue: None | "no_overlap" | "low_iou" | "multiple_candidates"
                 | "fm_load_error" | "fm_empty" | "fm_unknown_schema"
                 | "gdacs_empty",
        }

    Country-level failures (FM load error, empty FM, empty GDACS,
    unknown schema) return a single placeholder row carrying just
    ``iso3``, ``fm_level``, ``issue`` (+ optional ``detail``).
    """
    def placeholder(issue: str, **extra) -> list[dict]:
        return [{
            "iso3": iso3, "fm_level": fm_level, "issue": issue, **extra,
        }]

    try:
        fm = load_fieldmaps_adm(iso3, fm_level)
    except Exception as e:
        logger.warning(
            "FieldMaps load failed for %s adm%d: %s", iso3, fm_level, e,
        )
        return placeholder("fm_load_error", detail=str(e))

    if fm is None or len(fm) == 0:
        return placeholder("fm_empty")

    if fm_level == 0:
        # adm0 layer doesn't carry the adm{N}_pcode/name fields; fill
        # with the ISO3 so the schema downstream stays uniform.
        fm = fm.copy()
        fm["adm0_pcode"] = iso3
        if "adm0_name" not in fm.columns:
            fm["adm0_name"] = iso3
        fm_pcode_col, fm_name_col = "adm0_pcode", "adm0_name"
    else:
        fm_pcode_col, fm_name_col = fm_id_and_name_cols(fm, fm_level)
        if fm_pcode_col is None or fm_name_col is None:
            return placeholder(
                "fm_unknown_schema",
                detail=f"columns={list(fm.columns)}",
            )
        # Narrow fallback: a couple of iso3s (UMI, SJM) have NULL
        # adm1_name in FM and put the real subdivision name in
        # adm0_name (e.g. "Baker Island (USA)"). Fill nulls from
        # adm0_name ONLY for those iso3s — strict opt-in so this
        # doesn't accidentally paper over real FM data gaps elsewhere.
        if (iso3 in FM_ADM1_NAME_FALLBACK_ISOS
                and "adm0_name" in fm.columns
                and fm[fm_name_col].isna().any()):
            fm = fm.copy()
            fm[fm_name_col] = fm[fm_name_col].fillna(
                fm["adm0_name"].map(fallback_fm_name_from_adm0)
            )

    g = filter_gdacs_country(gdacs, iso3)
    if len(g) == 0:
        return placeholder(
            "gdacs_empty",
            detail=f"FM has {len(fm)} adm{fm_level} but GDACS has 0",
        )

    fm = fm[[fm_pcode_col, fm_name_col, "geometry"]].copy()
    g = g[[
        "GMI_ADMIN", "FIPS_ADMIN", "ADMIN_NAME",
        "TYPE_ENG", "geometry",
    ]].copy()

    # Reproject both to an equal-area CRS BEFORE computing areas /
    # intersection. IoU ratios are CRS-independent (numerator and
    # denominator scale the same way), but area math in a geographic
    # CRS (EPSG:4326) is meaningless in absolute terms AND throws a
    # pandas warning per call. EPSG:6933 (World Cylindrical Equal
    # Area) is a good general-purpose choice — area units are m².
    AREA_CRS = 6933
    if g.crs != fm.crs:
        g = g.to_crs(fm.crs)
    fm = fm.to_crs(AREA_CRS)
    g = g.to_crs(AREA_CRS)

    fm["_fm_idx"] = range(len(fm))
    fm["_fm_area"] = fm.geometry.area
    g["_g_idx"] = range(len(g))
    g["_g_area"] = g.geometry.area

    overlay = gpd.overlay(fm, g, how="intersection", keep_geom_type=True)
    overlay["_inter_area"] = overlay.geometry.area
    overlay["_iou"] = overlay["_inter_area"] / (
        overlay["_fm_area"] + overlay["_g_area"] - overlay["_inter_area"]
    )

    candidate_counts = (
        overlay[overlay["_iou"] > 0.01]
        .groupby("_fm_idx").size().to_dict()
    )
    best_rows = overlay.sort_values(
        "_iou", ascending=False,
    ).drop_duplicates("_fm_idx", keep="first")
    best_by_fm = best_rows.set_index("_fm_idx")

    rows: list[dict] = []
    n_g = len(g)
    n_fm = len(fm)
    for _, frow in fm.iterrows():
        fm_idx = frow["_fm_idx"]
        row = {
            "iso3": iso3,
            "fm_level": fm_level,
            "fm_pcode": frow[fm_pcode_col],
            "fm_name": frow[fm_name_col],
            "fm_area_m2": frow["_fm_area"],
            "fm_country_count": n_fm,
            "gdacs_country_count": n_g,
        }
        if fm_idx not in best_by_fm.index:
            row.update({
                "gmi_admin": None, "fips_admin": None,
                "gdacs_admin_name": None, "gdacs_admin_type": None,
                "iou": 0.0, "gdacs_area_m2": None,
                "n_candidates": 0, "issue": "no_overlap",
            })
            rows.append(row)
            continue

        best = best_by_fm.loc[fm_idx]
        n_cand = int(candidate_counts.get(fm_idx, 0))
        row.update({
            "gmi_admin": best["GMI_ADMIN"],
            "fips_admin": best["FIPS_ADMIN"],
            "gdacs_admin_name": best["ADMIN_NAME"],
            "gdacs_admin_type": best["TYPE_ENG"],
            "iou": float(best["_iou"]),
            "gdacs_area_m2": float(best["_g_area"]),
            "n_candidates": n_cand,
        })
        if row["iou"] < low_iou:
            row["issue"] = "low_iou"
        elif n_cand > 1:
            row["issue"] = "multiple_candidates"
        else:
            row["issue"] = None
        rows.append(row)

    return rows
