"""ONE-SHOT migration: existing storms.gdacs_fm_lookup → humanreview crosswalk CSV.

History
-------
The existing `storms.gdacs_fm_lookup` table in dev Postgres is the
cumulative output of the prior GDACS pipeline (policies +
per-row-notes + LLM iterations via the v1 GDACS lookup builder, now
archived at scripts/_archive/build_canonical_lookup.py).
The decisions baked into it are scattered across the TOML, the build
script logic, and the table itself.

We're migrating to the ADAM methodology: one crosswalk CSV containing
every FM↔GDACS spatial relationship with per-row decisions overlaid.

This script preserves all existing decisions by JOINing the dev DB
lookup table onto the fresh crosswalk on the encoding-immune keys
(iso3, fm_pcode, gmi_admin). Rows where the old lookup had a decision
attach the old `caveat_kind`/`caveat_note` as the new humanreview's
`caveat`, and the row's `classification_type` becomes `llm` (signaling
"this decision came from prior work, reviewer should ratify").

Rows in the fresh crosswalk that have NO matching row in the old
lookup stay at `classification_type=spatial` — these are either new
spatial pairs the old pipeline never considered, OR old pairs that
were dropped silently. The reviewer triages these in the humanreview
pass.

Orphans (old lookup rows that don't match any crosswalk row) are
written to a separate orphans file for investigation.

Output: `data/review/gdacs_fm_crosswalk_humanreview.csv` (gitignored).
Going forward, edit that CSV directly and never re-run this script —
re-running would clobber subsequent reviewer edits.

Run from repo root::

    uv run python scripts/_oneshot/migrate_gdacs_lookup_to_crosswalk_humanreview.py
"""

import argparse
import logging
import sys
from pathlib import Path

import coloredlogs
import ocha_stratus as stratus
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import text


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CROSSWALK = REPO_ROOT / "data" / "gdacs_fm_crosswalk.csv"
DEFAULT_OUT = (
    REPO_ROOT / "data" / "review" / "gdacs_fm_crosswalk_humanreview.csv"
)
DEFAULT_ORPHANS = (
    REPO_ROOT / "data" / "review"
    / "gdacs_fm_crosswalk_migration_orphans.csv"
)

JOIN_KEY = ["iso3", "fm_pcode", "gmi_admin"]

logger = logging.getLogger(__name__)


def main() -> int:
    coloredlogs.install(
        level="INFO",
        fmt="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--crosswalk", type=Path, default=DEFAULT_CROSSWALK,
                    help="fresh gdacs_fm_crosswalk.csv (built by "
                         "scripts/build_gdacs_fm_crosswalk.py)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help="output humanreview CSV path")
    ap.add_argument("--orphans", type=Path, default=DEFAULT_ORPHANS,
                    help="path for orphan old-lookup rows that don't "
                         "find a matching crosswalk row")
    ap.add_argument("--mode", choices=["dev", "prod"], default="dev",
                    help="DB stage to pull existing lookup from")
    args = ap.parse_args()

    if args.out.exists():
        logger.error(
            "Output %s already exists. Refusing to overwrite — this "
            "is a one-shot migration. Delete the file first if you "
            "really mean to re-run.", args.out,
        )
        return 1

    load_dotenv(REPO_ROOT / ".env")

    logger.info("Loading fresh crosswalk from %s", args.crosswalk)
    crosswalk = pd.read_csv(args.crosswalk, encoding="utf-8-sig")
    logger.info("  %d crosswalk rows across %d iso3s",
                len(crosswalk), crosswalk["iso3"].nunique())

    logger.info("Loading existing storms.gdacs_fm_lookup from %s DB",
                args.mode)
    engine = stratus.get_engine(stage=args.mode, write=False)
    with engine.connect() as conn:
        old = pd.read_sql(text("""
            SELECT iso3, admin_level, fm_pcode, fm_name,
                   gmi_admin, gdacs_admin_name,
                   caveat_kind, caveat_note
            FROM storms.gdacs_fm_lookup
        """), conn)
    logger.info("  %d existing lookup rows (%d adm0, %d adm1)",
                len(old),
                int((old["admin_level"] == 0).sum()),
                int((old["admin_level"] == 1).sum()))

    # The crosswalk is adm1 + fm_only + gdacs_only. adm0 rows in the
    # old lookup are synthesized by the lookup builder; the new
    # builder will regenerate them, so we don't migrate adm0 here.
    old_adm1 = old[old["admin_level"] == 1].copy()
    logger.info(
        "  Migrating only the %d adm1 rows from the old lookup "
        "(adm0 will be regenerated by the new builder)",
        len(old_adm1),
    )

    # ── JOIN on encoding-immune keys ──────────────────────────────
    # Both sides can have NULL gmi_admin (crosswalk: fm_only rows;
    # old lookup: fm_adm1_only policy rows). Pandas merge treats
    # NaN != NaN by default; use a sentinel so NaN-↔-NaN matches.
    SENTINEL = "__NA_KEY__"
    cw = crosswalk.copy()
    om = old_adm1.copy()
    for k in JOIN_KEY:
        cw[k] = cw[k].astype(object).where(cw[k].notna(), SENTINEL)
        om[k] = om[k].astype(object).where(om[k].notna(), SENTINEL)

    # Bring old decisions into the crosswalk + explicit "matched" flag
    # so we can tell apart "matched + clean" from "no match at all".
    old_decisions = om[JOIN_KEY + ["caveat_kind", "caveat_note"]].rename(
        columns={
            "caveat_kind": "_old_caveat_kind",
            "caveat_note": "_old_caveat_note",
        },
    )
    old_decisions["_matched_old"] = True
    merged = cw.merge(old_decisions, on=JOIN_KEY, how="left")

    # ── Promote existing decisions into the humanreview shape ──────
    # ANY crosswalk row that matched an old-lookup row is treated as
    # "the prior pipeline reviewed this row" → classification_type=llm.
    # That includes clean matches (no caveat) — the old build still
    # made a deliberate call to emit the row. The reviewer can flip
    # to classification_type=human when they ratify it manually.
    matched_old = merged["_matched_old"].fillna(False).astype(bool)
    # Old caveat_note (if any) becomes the human-facing caveat
    if "caveat" not in merged.columns:
        merged["caveat"] = pd.NA
    has_old_caveat = matched_old & merged["_old_caveat_note"].notna()
    merged.loc[has_old_caveat, "caveat"] = (
        merged.loc[has_old_caveat, "_old_caveat_note"]
    )
    # classification_type: flip to llm on ALL matched rows (clean or not)
    merged.loc[matched_old, "classification_type"] = "llm"
    # Preserve the old kind as audit metadata in a sidecar column.
    # The new pipeline derives caveat_kind from status; this stays
    # for human readability of what the old build thought.
    merged = merged.rename(
        columns={"_old_caveat_kind": "legacy_caveat_kind"},
    )
    merged = merged.drop(columns=["_old_caveat_note", "_matched_old"])

    # Add an empty internal_note column (matches ADAM humanreview)
    merged["internal_note"] = pd.NA

    # Restore NaN keys
    for k in JOIN_KEY:
        merged[k] = merged[k].where(merged[k] != SENTINEL, None)

    # ── Report orphans (old rows with no crosswalk match) ─────────
    # Some "orphans" are EXPECTED: rows in fm_adm1_only / country_only
    # / no_fm_source / needs_manual_mapping countries with NULL
    # gmi_admin represent "FM-only by policy" in the old lookup. The
    # new lookup builder re-synthesizes these from policy at build
    # time, so they don't need migration to the crosswalk. We still
    # attach any meaningful caveat_note from them to the first
    # matching crosswalk row for the same FM (so reviewers see them).
    cw_keys = set(map(tuple, cw[JOIN_KEY].values.tolist()))
    om_keys = set(map(tuple, om[JOIN_KEY].values.tolist()))
    orphan_keys = om_keys - cw_keys

    # Split into expected (NULL gmi_admin) vs unexpected
    expected_orphan_kinds = (
        "fm_only_policy", "country_only", "needs_manual_mapping",
    )
    expected_orphan_rows = old_adm1[
        old_adm1["gmi_admin"].isna()
        & old_adm1["caveat_kind"].isin(expected_orphan_kinds)
    ].copy()
    # Per-FM caveat preservation: for each (iso3, fm_pcode) in expected
    # orphans, attach the caveat_note to the FIRST crosswalk row for
    # that FM (preferring overlap rows that exist; this matches how
    # the new lookup builder picks up the per-FM caveat).
    preserved = 0
    for (iso3, fm_pcode), grp in expected_orphan_rows.groupby(
        ["iso3", "fm_pcode"], dropna=False,
    ):
        if pd.isna(fm_pcode):
            continue
        cveat = grp["caveat_note"].dropna().head(1)
        if cveat.empty:
            continue
        # Find the first matching crosswalk row for this FM
        cw_mask = (
            (merged["iso3"] == iso3)
            & (merged["fm_pcode"] == fm_pcode)
            & merged["caveat"].isna()
        )
        if cw_mask.any():
            first_idx = merged.index[cw_mask][0]
            merged.at[first_idx, "caveat"] = cveat.iloc[0]
            merged.at[first_idx, "classification_type"] = "llm"
            preserved += 1

    # The "true orphan" set is just the old rows we couldn't migrate
    # AND that aren't already covered by the expected-orphan path.
    expected_orphan_keys = set(
        map(tuple, expected_orphan_rows[JOIN_KEY].fillna("__NA_KEY__")
            .values.tolist())
    )
    true_orphan_keys = orphan_keys - expected_orphan_keys
    if true_orphan_keys:
        logger.warning(
            "%d UNEXPECTED orphan rows in the old lookup — writing "
            "to %s for investigation. Likely shapefile drift in "
            "GMI_ADMIN codes or FM pcode changes.",
            len(true_orphan_keys), args.orphans,
        )
        orphan_mask = om.apply(
            lambda r: tuple(r[k] for k in JOIN_KEY) in true_orphan_keys,
            axis=1,
        )
        orphans = old_adm1.loc[orphan_mask[orphan_mask].index].copy()
        args.orphans.parent.mkdir(parents=True, exist_ok=True)
        orphans.to_csv(args.orphans, index=False, encoding="utf-8-sig")
    else:
        logger.info(
            "No unexpected orphans (all %d unmatched old rows are "
            "fm_only-by-policy in fm_adm1_only/country_only/"
            "needs_manual_mapping countries, regenerated from policy "
            "by the new lookup builder).",
            len(orphan_keys),
        )

    # ── Summary ─────────────────────────────────────────────────────
    spatial_only = int((merged["classification_type"] == "spatial").sum())
    llm_inherited = int((merged["classification_type"] == "llm").sum())
    logger.info(
        "Migration summary:\n"
        "  Crosswalk rows total:                  %d\n"
        "  Now classification_type=spatial:       %d\n"
        "  Now classification_type=llm (inherited): %d\n"
        "  Expected (policy-driven) orphans:      %d\n"
        "  Per-FM caveats preserved from those:   %d\n"
        "  True orphans (unexpected):             %d",
        len(merged), spatial_only, llm_inherited,
        len(expected_orphan_rows), preserved,
        len(true_orphan_keys),
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    merged.to_csv(args.out, index=False, encoding="utf-8-sig")
    logger.info("Wrote %d rows to %s", len(merged), args.out)
    logger.info(
        "Going forward, edit %s directly (NEVER open in Excel — use "
        "a text editor; Excel-on-Mac mangles the encoding on save).",
        args.out,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
