"""Spatial matching: FieldMaps adm-1 polygons ↔ ADAM admin polygons.

============================================================================
⚠️  EXPLORATORY / REVIEW-ONLY — NOT live production monitoring.
----------------------------------------------------------------------------
This module is NOT used by the production lookup or the real-time pipelines.
The production `storms.adam_fm_lookup` is built by
`scripts/build_adam_fm_lookup.py` from the human-reviewed crosswalk
(`data/review/adam_fm_crosswalk_humanreview.csv`); that crosswalk is
generated by `scripts/build_adam_fm_crosswalk.py`, which runs its own
overlay and emits EVERY FM×ADAM pair — it does not call this module.

Only caller after this PR: the human-review report pipeline
(`scripts/build_adam_review_artifacts.py` → `exploration/review_report_adam
.qmd`), which uses `match_country`. (The legacy v1 builder — now archived at
`scripts/_archive/build_adam_fm_lookup.py` — used both functions; with it
archived, `match_per_adam_admin` has no caller.)

Consequence: the IoU best-pick tie-break below is review-only and left as-is
on purpose (see PR #19 discussion). A later PR will relocate this out of
`src/static/` so the exploratory↔production boundary is structural.
============================================================================

Mirror of :mod:`src.static.gdacs.matcher` for the FM↔ADAM bridge.
Two iteration modes:

  - :func:`match_country` — iterates the FM side, picks best-IoU ADAM
    polygon per FM unit. Used by the review-artifacts builder (per-FM
    diagnostics).
  - :func:`match_per_adam_admin` — iterates the ADAM side, picks
    best-IoU FM polygon per ADAM polygon. Was used by the v1 lookup build
    (archived in PR #19) to avoid name-fanout double-counting; currently
    has no caller (kept for the per-source approach a future production
    rebuild may adopt).

The ADAM admin layer is fixed at admin-1 (no hierarchy); only the
FM-side level is configurable via
:func:`src.static.adam.inputs.resolve_adam_fm_level`.
"""

from __future__ import annotations

import logging

import geopandas as gpd

from src.static.adam.admin import filter_adam_country
from src.static.adam.inputs import (
    FM_ADM1_NAME_FALLBACK_ISOS,
    fallback_fm_name_from_adm0,
    fm_id_and_name_cols,
    load_fieldmaps_adm,
)


logger = logging.getLogger(__name__)


def match_country(
    iso3: str,
    adam_admin: gpd.GeoDataFrame,
    low_iou: float = 0.5,
    fm_level: int = 1,
) -> list[dict]:
    """One row per FieldMaps unit-at-``fm_level`` for ``iso3``.

    Per-FM iteration: for each FM polygon, picks the ADAM admin
    polygon that maximises IoU. Returns one row per FM polygon (no-
    overlap orphans included so the caller can flag them).

    Used by ``build_adam_review_artifacts.py`` for per-FM diagnostics
    in the qmd. The lookup build uses :func:`match_per_adam_admin`
    instead because per-source iteration avoids the name-fanout
    downstream-join class of bug.

    Returned dict shape::

        {
          iso3, fm_level, fm_pcode, fm_name, fm_area_m2,
          fm_country_count, adam_admin_count,
          adam_admin_id, adam_admin_name, adam_admin_altname,
          iou, adam_area_m2, n_candidates,
          issue: None | "no_overlap" | "low_iou" | "multiple_candidates"
                 | "fm_load_error" | "fm_empty" | "fm_unknown_schema"
                 | "adam_admin_empty",
        }

    Country-level failures return a single placeholder row carrying
    just ``iso3``, ``fm_level``, ``issue`` (+ optional ``detail``).
    """
    def placeholder(issue: str, **extra) -> list[dict]:
        return [{
            "iso3": iso3, "fm_level": fm_level, "issue": issue, **extra,
        }]

    try:
        fm = load_fieldmaps_adm(iso3, fm_level)
    except Exception as e:
        logger.warning(
            "FieldMaps load failed for %s adm%d: %s", iso3, fm_level, e,
        )
        return placeholder("fm_load_error", detail=str(e))

    if fm is None or len(fm) == 0:
        return placeholder("fm_empty")

    if fm_level == 0:
        fm = fm.copy()
        fm["adm0_pcode"] = iso3
        if "adm0_name" not in fm.columns:
            fm["adm0_name"] = iso3
        fm_pcode_col, fm_name_col = "adm0_pcode", "adm0_name"
    else:
        fm_pcode_col, fm_name_col = fm_id_and_name_cols(fm, fm_level)
        if fm_pcode_col is None or fm_name_col is None:
            return placeholder(
                "fm_unknown_schema",
                detail=f"columns={list(fm.columns)}",
            )
        if (iso3 in FM_ADM1_NAME_FALLBACK_ISOS
                and "adm0_name" in fm.columns
                and fm[fm_name_col].isna().any()):
            fm = fm.copy()
            fm[fm_name_col] = fm[fm_name_col].fillna(
                fm["adm0_name"].map(fallback_fm_name_from_adm0)
            )

    aa = filter_adam_country(adam_admin, iso3)
    if len(aa) == 0:
        return placeholder(
            "adam_admin_empty",
            detail=f"FM has {len(fm)} adm{fm_level} but ADAM admin has 0",
        )

    fm = fm[[fm_pcode_col, fm_name_col, fm.geometry.name]].copy()
    # ADAM admin layer's active geometry col is named `shape` (not
    # `geometry`), AND both layers use lowercase `adm1_id`/`adm1_name`
    # so overlay() would collide. Rename ADAM cols to `_aa_*` and the
    # geom to `geometry` so the overlay output is unambiguous. We map
    # them back to the public adam_* names at row-emission time.
    aa = aa[[
        "adm1_id", "adm1_name", "adm1_altnm", aa.geometry.name,
    ]].copy()
    if aa.geometry.name != "geometry":
        aa = aa.rename_geometry("geometry")
    if fm.geometry.name != "geometry":
        fm = fm.rename_geometry("geometry")
    aa = aa.rename(columns={
        "adm1_id": "_aa_id",
        "adm1_name": "_aa_name",
        "adm1_altnm": "_aa_altnm",
    })

    # Equal-area projection before area math — same reasoning as the
    # GDACS matcher. EPSG:6933 World Cylindrical Equal Area; units m².
    # IoU ratios are CRS-independent so the reprojection only matters
    # for the absolute area columns we surface to the qmd.
    AREA_CRS = 6933
    if aa.crs != fm.crs:
        aa = aa.to_crs(fm.crs)
    fm = fm.to_crs(AREA_CRS)
    aa = aa.to_crs(AREA_CRS)

    fm["_fm_idx"] = range(len(fm))
    fm["_fm_area"] = fm.geometry.area
    aa["_aa_idx"] = range(len(aa))
    aa["_aa_area"] = aa.geometry.area

    overlay = gpd.overlay(fm, aa, how="intersection", keep_geom_type=True)
    overlay["_inter_area"] = overlay.geometry.area
    overlay["_iou"] = overlay["_inter_area"] / (
        overlay["_fm_area"] + overlay["_aa_area"] - overlay["_inter_area"]
    )

    candidate_counts = (
        overlay[overlay["_iou"] > 0.01]
        .groupby("_fm_idx").size().to_dict()
    )
    best_rows = overlay.sort_values(
        "_iou", ascending=False,
    ).drop_duplicates("_fm_idx", keep="first")
    best_by_fm = best_rows.set_index("_fm_idx")

    rows: list[dict] = []
    n_aa = len(aa)
    n_fm = len(fm)
    for _, frow in fm.iterrows():
        fm_idx = frow["_fm_idx"]
        row = {
            "iso3": iso3,
            "fm_level": fm_level,
            "fm_pcode": frow[fm_pcode_col],
            "fm_name": frow[fm_name_col],
            "fm_area_m2": frow["_fm_area"],
            "fm_country_count": n_fm,
            "adam_admin_count": n_aa,
        }
        if fm_idx not in best_by_fm.index:
            row.update({
                "adam_admin_id": None, "adam_admin_name": None,
                "adam_admin_altname": None,
                "iou": 0.0, "adam_area_m2": None,
                "n_candidates": 0, "issue": "no_overlap",
            })
            rows.append(row)
            continue

        best = best_by_fm.loc[fm_idx]
        n_cand = int(candidate_counts.get(fm_idx, 0))
        row.update({
            "adam_admin_id": best["_aa_id"],
            "adam_admin_name": best["_aa_name"],
            "adam_admin_altname": best["_aa_altnm"],
            "iou": float(best["_iou"]),
            "adam_area_m2": float(best["_aa_area"]),
            "n_candidates": n_cand,
        })
        if row["iou"] < low_iou:
            row["issue"] = "low_iou"
        elif n_cand > 1:
            row["issue"] = "multiple_candidates"
        else:
            row["issue"] = None
        rows.append(row)

    return rows


def match_per_adam_admin(
    iso3: str,
    adam_admin: gpd.GeoDataFrame,
    low_iou: float = 0.5,
    fm_level: int = 1,
) -> list[dict]:
    """Per-ADAM-admin variant of :func:`match_country`.

    Iterates the ADAM admin side, emits one row per ADAM admin polygon
    with the best-IoU FM polygon.

    Why this exists: the per-FM iteration in :func:`match_country` is
    safe for code-keyed sources (GDACS' ``gmi_admin``) because each
    source code is unique in the source layer, so even when IoU picks
    a bad-but-best FM partner each source row still joins 1:1
    downstream. ADAM joins by NAME and the same name can appear on
    multiple per-FM lookup rows (FM finer than ADAM admin for BHS-like
    territories), which fans out the join and double-counts. The
    per-ADAM iteration eliminates the fanout structurally: each
    ``adam_admin_id`` appears at most once in the output, so each
    ADAM name resolves to exactly one ``fm_pcode``.

    Returned dict shape (one row per ADAM admin polygon)::

        {
          iso3, fm_level,
          adam_admin_id, adam_admin_name, adam_admin_altname,
          adam_area_m2,
          fm_pcode, fm_name, fm_area_m2,
          iou, n_fm_candidates, adam_admin_count, fm_country_count,
          issue: None | "low_iou" | "multiple_candidates"
                 | "no_overlap" | "fm_load_error" | "fm_empty"
                 | "adam_admin_empty" | "fm_unknown_schema",
        }
    """
    def placeholder(issue: str, **extra) -> list[dict]:
        return [{
            "iso3": iso3, "fm_level": fm_level, "issue": issue, **extra,
        }]

    try:
        fm = load_fieldmaps_adm(iso3, fm_level)
    except Exception as e:
        logger.warning(
            "FieldMaps load failed for %s adm%d: %s", iso3, fm_level, e,
        )
        return placeholder("fm_load_error", detail=str(e))

    if fm is None or len(fm) == 0:
        return placeholder("fm_empty")

    if fm_level == 0:
        fm = fm.copy()
        fm["adm0_pcode"] = iso3
        if "adm0_name" not in fm.columns:
            fm["adm0_name"] = iso3
        fm_pcode_col, fm_name_col = "adm0_pcode", "adm0_name"
    else:
        fm_pcode_col, fm_name_col = fm_id_and_name_cols(fm, fm_level)
        if fm_pcode_col is None or fm_name_col is None:
            return placeholder(
                "fm_unknown_schema",
                detail=f"columns={list(fm.columns)}",
            )
        if (iso3 in FM_ADM1_NAME_FALLBACK_ISOS
                and "adm0_name" in fm.columns
                and fm[fm_name_col].isna().any()):
            fm = fm.copy()
            fm[fm_name_col] = fm[fm_name_col].fillna(
                fm["adm0_name"].map(fallback_fm_name_from_adm0)
            )

    aa = filter_adam_country(adam_admin, iso3)
    if len(aa) == 0:
        return placeholder(
            "adam_admin_empty",
            detail=f"FM has {len(fm)} adm{fm_level} but ADAM admin has 0",
        )

    # Identical preparation as match_country — same rename + reproject
    # so the IoU math is consistent across the two iteration modes.
    fm = fm[[fm_pcode_col, fm_name_col, fm.geometry.name]].copy()
    aa = aa[[
        "adm1_id", "adm1_name", "adm1_altnm", aa.geometry.name,
    ]].copy()
    if aa.geometry.name != "geometry":
        aa = aa.rename_geometry("geometry")
    if fm.geometry.name != "geometry":
        fm = fm.rename_geometry("geometry")
    aa = aa.rename(columns={
        "adm1_id": "_aa_id",
        "adm1_name": "_aa_name",
        "adm1_altnm": "_aa_altnm",
    })

    AREA_CRS = 6933
    if aa.crs != fm.crs:
        aa = aa.to_crs(fm.crs)
    fm = fm.to_crs(AREA_CRS)
    aa = aa.to_crs(AREA_CRS)

    fm["_fm_idx"] = range(len(fm))
    fm["_fm_area"] = fm.geometry.area
    aa["_aa_idx"] = range(len(aa))
    aa["_aa_area"] = aa.geometry.area

    overlay = gpd.overlay(fm, aa, how="intersection", keep_geom_type=True)
    overlay["_inter_area"] = overlay.geometry.area
    overlay["_iou"] = overlay["_inter_area"] / (
        overlay["_fm_area"] + overlay["_aa_area"] - overlay["_inter_area"]
    )

    # n_fm_candidates: how many FM polygons substantially overlap this
    # ADAM polygon — surfaces ADAM units that straddle a recent FM
    # admin-reform boundary (analogue of n_candidates on the per-FM
    # side).
    candidate_counts = (
        overlay[overlay["_iou"] > 0.01]
        .groupby("_aa_idx").size().to_dict()
    )
    best_rows = overlay.sort_values(
        "_iou", ascending=False,
    ).drop_duplicates("_aa_idx", keep="first")
    best_by_aa = best_rows.set_index("_aa_idx")

    rows: list[dict] = []
    n_aa = len(aa)
    n_fm = len(fm)
    for _, arow in aa.iterrows():
        a_idx = arow["_aa_idx"]
        row = {
            "iso3": iso3,
            "fm_level": fm_level,
            "adam_admin_id": arow["_aa_id"],
            "adam_admin_name": arow["_aa_name"],
            "adam_admin_altname": arow["_aa_altnm"],
            "adam_area_m2": float(arow["_aa_area"]),
            "fm_country_count": n_fm,
            "adam_admin_count": n_aa,
        }
        if a_idx not in best_by_aa.index:
            row.update({
                "fm_pcode": None, "fm_name": None, "fm_area_m2": None,
                "iou": 0.0, "n_fm_candidates": 0, "issue": "no_overlap",
            })
            rows.append(row)
            continue

        best = best_by_aa.loc[a_idx]
        n_cand = int(candidate_counts.get(a_idx, 0))
        row.update({
            "fm_pcode": best[fm_pcode_col],
            "fm_name": best[fm_name_col],
            "fm_area_m2": float(best["_fm_area"]),
            "iou": float(best["_iou"]),
            "n_fm_candidates": n_cand,
        })
        if row["iou"] < low_iou:
            row["issue"] = "low_iou"
        elif n_cand > 1:
            row["issue"] = "multiple_candidates"
        else:
            row["issue"] = None
        rows.append(row)

    return rows
